// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: client/redis/redis.proto

package redis

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RedisOptions struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisOptions) Reset()         { *m = RedisOptions{} }
func (m *RedisOptions) String() string { return proto.CompactTextString(m) }
func (*RedisOptions) ProtoMessage()    {}
func (*RedisOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4277b20bffc621f, []int{0}
}
func (m *RedisOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisOptions.Unmarshal(m, b)
}
func (m *RedisOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisOptions.Marshal(b, m, deterministic)
}
func (m *RedisOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisOptions.Merge(m, src)
}
func (m *RedisOptions) XXX_Size() int {
	return xxx_messageInfo_RedisOptions.Size(m)
}
func (m *RedisOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisOptions.DiscardUnknown(m)
}

var xxx_messageInfo_RedisOptions proto.InternalMessageInfo

func (m *RedisOptions) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*RedisOptions)(nil), "ops.bot.client.redis.RedisOptions")
}

func init() { proto.RegisterFile("client/redis/redis.proto", fileDescriptor_d4277b20bffc621f) }

var fileDescriptor_d4277b20bffc621f = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2f, 0x4a, 0x4d, 0xc9, 0x2c, 0x86, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0x22, 0xf9, 0x05, 0xc5, 0x7a, 0x49, 0xf9, 0x25, 0x7a, 0x10, 0x15, 0x7a, 0x60, 0x39, 0x25,
	0x05, 0x2e, 0x9e, 0x20, 0x10, 0xc3, 0xbf, 0xa0, 0x24, 0x33, 0x3f, 0xaf, 0x58, 0x48, 0x80, 0x8b,
	0xb9, 0xb4, 0x28, 0x47, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x74, 0x92, 0x89, 0x92,
	0xca, 0x2f, 0x28, 0xd6, 0x4d, 0xca, 0x2f, 0xd1, 0x47, 0x36, 0xdb, 0x1a, 0x4c, 0x26, 0xb1, 0x81,
	0x0d, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x77, 0x41, 0x91, 0x78, 0x00, 0x00, 0x00,
}
